<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Action' => '操作',
    'Amount of the transaction' => '交易金额',
    'Answered the question' => '回答问题',
    'Ask questions' => '提问',
    'Clean' => '取消',
    'Coin Manage' => '金币管理',
    'Coin Recharge' => '金币重置',
    'Created At' => '创建时间',
    'Currency' => '国家',
    'Gateway' => '支付网关',
    'ID' => '',
    'Money' => '金额',
    'Name' => '',
    'Payment' => '支付',
    'Payment Id' => '流水号',
    'Recharge' => '立即充值',
    'Source Subject' => '',
    'Submit' => '',
    'Trade State' => '交易状态',
    'Trade Type' => '交易类型',
    'Transaction Hour' => '交易时间',
    'Updated At' => '更新时间',
    'User ID' => '',
    'Your current coins are:' => '您当前的金币数为：',
    'answer is adopted' => '答案被采纳',
];
